name: "ssh deploy"
description: "NodeJS action for FAST deployment with rsync/ssh"
author: "Sekkmer"
inputs:
  SSH_PRIVATE_KEY: # Private Key
    description: "Private Key"
    required: true
  SSH_CONFIG:
    description: "SSH config file template"
    required: true
  SOURCE:
    description: "Source directory"
    required: false
    default: ""
  TARGET:
    description: "Target directory"
    required: false
    default: ""
  ARGS:
    description: "Arguments to pass to rsync"
    required: false
    default: "-rltgoDzvO"
  EXCLUDE:
    description: "An array of folder to exclude"
    required: false
    default: ""
outputs:
  status:
    description: "Status"
runs:
  using: "node12"
  main: "dist/index.js"
branding:
  color: "green"
  icon: "truck"
